vinte = ('Flamengo', 'Cruzeiro', 'Palmeiras', 'Mirassol', 'Botafogo', 'Esporte Clube Bahia', 'São Paulo', 'Fluminense', 'Red Bull Bragantino', 'Grêmio', 'Vasco da Gama', 'Corinthians', 'Ceará', 'Atlético Mineiro', 'Sport', 'Santos', 'Juventude', 'Vitória', 'Fortaleza', 'Recife')
print('Lista de times do Brasileirão 2025:')
print('-'*150)
print(f'Os cinco primeiros colocados são: {vinte[0:5]}')
print('-'*150)
print(f'Os quatro últimos colocados são: {vinte[-4:]}')
print('-'*150)
print(f'Times em ordem alfabética: {sorted(vinte)}')
print('-'*150)
print(f'O Corinthians está na {vinte.index("Corinthians")+1}ª posição.')
print('-'*150)
